config/routes.rb
Rails.application.routes.draw do
  root 'trips#index'

  resources :trips do
    resources :location
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :location
  validates_uniqueness_of :address
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :trip
  has_one :address, dependent: :destroy
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  serialize :items, Array
  has_many :locations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :location, only: [:edit, :show, :update, :destroy]

  def index
    @trip = Trip.find(params[:trip_id])
    @locations = Location.all
  end

  def new
    @trip = Trip.find(params[:trip_id])
    @location = Location.new
  end

  def create
    @trip = Trip.find(params[:trip_id])
    @location = Location.new(location_params)
    if @location.save
      redirect_to locations_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @location.update(location_params)
      redirect_to location_path(@location)
    else
      render :edit
    end
  end

  def show
    @trip = Trip.find(params[:trip_id])
  end

  def destroy
    if @location.destroy
      redirect_to locations_path
    else
      redirect_to locations_path
    end
  end

private

  def location_params
    params.require(:location)
      .permit(
        :name,
        :distance,
        :date
      )
  end

  def location
    @location = Location.find_by(id: params[:id])
  end

end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :trip, only: [:edit, :show, :update, :destroy]

  def index
    @trips = Trip.all
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    if @trip.save
      redirect_to trips_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @trip.update(trip_params)
      redirect_to trip_path(@trip)
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    if @trip.destroy
      redirect_to trip_path
    else
      redirect_to trip_path
    end
  end

private

  def trip_params
    params.require(:trip)
      .permit(
        :name,
        :distance,
        :date
      )
  end

  def trip
    @trip = Trip.find_by(id: params[:id]) || Trip.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TripPlanner</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/locations/_form.html.erb
<%= form_for @location do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :distance %>
  <%= f.text_field :distance %>

  <%= f.label :date %>
  <%= f.text_field :date %>
  <%= f.submit %>
<% end %>

app/views/locations/edit.html.erb
<h1>Edit <%= @location.name %></h1>
<%= render partial: 'form' %>

app/views/locations/index.html.erb
<h1>Locations List</h1>

<% if @locations.any? %>
  <!-- loop the schools and display the links to each one -->
  <ul>
    <% @locations.each do |location| %>
      <li>
      <%= link_to location.name, location_path(location) %>
      <!--  <a href='/school/:id'>Neumont</a> -->
      </li>
    <% end %>
  </ul>
  <% else %>
  <h3>No locations found, please create one!</h3>
<% end %>

<%= link_to 'New Location Plan', new_location_path %>

app/views/locations/new.html.erb
<h1>New Location</h1>
<hr />

<%= render partial: 'form' %>

app/views/locations/show.html.erb
<h1><%= @location.name %></h1>
<hr />
<h2>Location name: <%= @location.name %></h2>
<h2>Location distance: <%= @location.distance %></h2>
<h2>Location date: <%= @location.date %></h2>

<%= link_to 'See All Locations', locations_path %>
<%= link_to 'Edit Location Plan', edit_location_path %>
<%= link_to 'Delete Location', location_path(@location), method: :delete %>

app/views/trips/_form.html.erb
<%= form_for @trip do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :distance %>
  <%= f.text_field :distance %>

  <%= f.label :date %>
  <%= f.text_field :date %>
  <%= f.submit %>
<% end %>

app/views/trips/_trips.html.erb
<h2>Trips List</h2>

app/views/trips/edit.html.erb
<h1>Trips#edit</h1>
<p>Find me in app/views/trips/edit.html.erb</p>

app/views/trips/index.html.erb
<h1>Trips List</h1>

<% if @trips.any? %>
  <!-- loop the schools and display the links to each one -->
  <ul>
    <% @trips.each do |trip| %>
      <li>
      <%= link_to trip.name, trip_path(trip) %>
      <!--  <a href='/school/:id'>Neumont</a> -->
      </li>
    <% end %>
  </ul>
  <% else %>
  <h3>No trips found, please create one!</h3>
<% end %>

<%= link_to 'New Trip Plan', new_trip_path %>

app/views/trips/new.html.erb
<h1>New Trip</h1>
<hr />

<%= render partial: 'form' %>

app/views/trips/show.html.erb
<h1><%= @trip.name %></h1>
<hr />
<h2><%= @trip.distance %></h2>